# The configuration assumes a private configuration that looks like the following has been applied manually.
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: https
# data:
#   cert.pem:
#   key.pem:
#   ca.pem:

---
# Expose the Elypia Frontend
# If using Google Kubernetes Engine, this will create a new static IP,
# make sure to update your DNS records to direct to it.
apiVersion: v1
kind: Service
metadata:
  name: elypia-website-service
  labels:
    app: elypia-website
spec:
  type: LoadBalancer
  selector:
    app: elypia-website
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
---
# Deploy the Elypia Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elypia-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elypia-website
  template:
    metadata:
      labels:
        app: elypia-website
    spec:
      volumes:
        - name: ssl-certs
          secret:
            secretName: https
      containers:
        - name: elypia-website
          image: us.gcr.io/elypia/elypia-website:{{CI_COMMIT_TAG}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/nginx/certs/
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
---
