# The configuration assumes the Kubernetes cluster has Helm and Tiller
# installed with the following charts (packages):
# * nginx-ingress - Load balancer to internal web application instances.
# * cert-manager - Automatically provision Let's Encrypt certificates.
#
# See ./kubernetes-init.sh

---
# Create Namespace for elypia-website
apiVersion: v1
kind: Namespace
metadata:
  name: elypia-website
---
# Deploy the Elypia Website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elypia-website-deployment
  namespace: elypia-website
  labels:
    app: elypia-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elypia-website
  template:
    metadata:
      labels:
        app: elypia-website
    spec:
      containers:
        - name: elypia-website
          image: us.gcr.io/elypia/elypia-website:{{CI_COMMIT_TAG}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
            httpGet:
              path: /index.html
              port: 80
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
            httpGet:
              path: /index.html
              port: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 1m
            limits:
              memory: 512Mi
              cpu: 200m
---
# Expose the Elypia Website
apiVersion: v1
kind: Service
metadata:
  name: elypia-website-service
  namespace: elypia-website
spec:
  selector:
    app: elypia-website
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
# Exposed public endpoint for users to connect.
# On GKE this will allocate an IP which should be added
# to the DNS records associated with the domain defined.
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elypia-website-ingress
  namespace: elypia-website
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/server-alias: "www.elypia.org"
spec:
  tls:
    - secretName: letsencrypt-tls
      hosts:
        - elypia.org
        - www.elypia.org
  rules:
    - host: elypia.org
      http:
        paths:
          - path: /
            backend:
              serviceName: elypia-website-service
              servicePort: 80
---
# Automatically provision Let's Encrypt certificates.
# Staging: https://acme-staging-v02.api.letsencrypt.org/directory
# Production: https://acme-v02.api.letsencrypt.org/directory
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: elypia-website
spec:
  acme:
    email: seth@elypia.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
      - http01:
          ingress:
            class: nginx
---
